#![cfg_attr(feature = "no_std", no_std)]

//! # Extrum
//!
//! A macro for defining enum-like types with a specified underlying integer type.
//! It generates a transparent wrapper struct with associated constants, conversion
//! methods, debug formatting, and equality comparisons with the base type.
//!
//! Additionally, helper macros like [`implement_display!`] are provided to add
//! common trait implementations after the type definition.
//!
//! ## Example
//!
//! ```
//! use extrum::{extrum, implement_display};
//!
//! extrum! {
//!     #[derive(PartialEq)]
//!     enum MyEnum: u8 {
//!         FOO = 1,
//!         BAR = 2,
//!     }
//! }
//!
//! implement_display![MyEnum];
//!
//! assert_eq!(MyEnum::FOO, MyEnum::from_raw(1));
//! assert_eq!(MyEnum::BAR.into_raw(), 2);
//! assert_eq!(MyEnum::FOO.name(), "FOO");
//! assert_eq!(format!("{}", MyEnum::BAR), "BAR");
//! ```

/// Defines a strongly-typed wrapper around an integer base type.
///
/// The macro generates:
/// - A transparent `struct` with the given visibility and name.
/// - `pub const` associated constants for each variant.
/// - `from_raw` / `into_raw` conversion methods.
/// - A `name` method returning the variant name as a string.
/// - `From` implementations for conversions to/from the base type.
/// - `Debug` implementation that prints variant names or unknown values.
/// - `Eq` and cross-type `PartialEq` implementations with the base type.
///
/// # Syntax
///
/// ```text
/// extrum! {
///     $(#[$struct_attrs:meta])*
///     $vis enum $name:ident : $base_ty:ty {
///         $variant:ident = $value:expr, *
///     }
/// }
/// ```
///
/// # Example
///
/// ```
/// # use extrum::extrum;
/// extrum! {
///     #[derive(PartialEq, Clone, Copy)]
///     pub enum StatusCode: u16 {
///         OK = 200,
///         NOT_FOUND = 404,
///     }
/// }
///
/// let ok = StatusCode::OK;
/// assert_eq!(ok.into_raw(), 200);
/// assert_eq!(StatusCode::from_raw(404), StatusCode::NOT_FOUND);
/// assert_eq!(format!("{:?}", ok), "StatusCode::OK");
/// ```
#[macro_export]
macro_rules! extrum
{
    (
        $(#[$struct_attrs:meta])*
        $vis:vis enum $name:ident : $base_ty:ty
        {
            $(
                $variant:ident = $value:expr
            ),* $(,)?
        }
    )
    =>
    {
        $(#[$struct_attrs])*
        #[repr(transparent)]
        $vis struct $name($base_ty);

        impl $name
        {
            $(
                pub const $variant: Self = Self($value);
            )*

            #[inline(always)]
            pub const fn from_raw(value: $base_ty) -> Self
            {
                Self(value)
            }

            #[inline(always)]
            pub const fn into_raw(self) -> $base_ty
            {
                self.0
            }

            #[inline(always)]
            pub const fn is_known(&self) -> bool
            {
                false $(|| self.0 == $value)*
            }

            pub fn name(&self) -> &'static str
            {
                $(
                    if self.0 == $value
                    {
                        return stringify!($variant);
                    }
                )*

                "Unknown"
            }
        }

        impl From<$base_ty> for $name
        {
            #[inline(always)]
            fn from(value: $base_ty) -> Self
            {
                Self(value)
            }
        }

        impl From<$name> for $base_ty
        {
            #[inline(always)]
            fn from(value: $name) -> Self
            {
                value.0
            }
        }

        impl core::fmt::Debug for $name
        {
            fn fmt(
                &self,
                f: &mut core::fmt::Formatter<'_>
            ) -> core::fmt::Result
            {
                $(
                    if self.0 == $value
                    {
                        return f.write_str(
                            concat!(
                                stringify!($name),
                                "::",
                                stringify!($variant)
                            )
                        );
                    }
                )*

                write!(
                    f,
                    "{}({})",
                    stringify!($name),
                    self.0
                )
            }
        }

        impl Eq for $name {}

        impl PartialEq<$base_ty> for $name
        {
            #[inline(always)]
            fn eq(&self, other: &$base_ty) -> bool
            {
                self.0 == *other
            }
        }

        impl PartialEq<$name> for $base_ty
        {
            #[inline(always)]
            fn eq(&self, other: &$name) -> bool
            {
                *self == other.0
            }
        }
    };
}

/// Implements [`core::fmt::Display`] for an `extrum!`-defined type.
///
/// This macro uses the [`name`] method generated by `extrum!` to print the
/// variant name for known values, or `"Unknown"` for unknown values.
///
/// # Example
///
/// ```
/// # use extrum::{extrum, implement_display};
/// 
/// extrum! {
///     #[derive(PartialEq)]
///     enum Color: u8 {
///         RED = 1,
///         GREEN = 2,
///     }
/// }
///
/// implement_display![Color];
///
/// assert_eq!(format!("{}", Color::RED), "RED");
/// assert_eq!(format!("{}", Color::GREEN), "GREEN");
/// ```
///
/// [`name`]: #method.name
#[macro_export]
macro_rules! implement_display
{
    ($name:ident) =>
    {
        impl core::fmt::Display for $name
        {
            fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result
            {
                f.write_str(self.name())
            }
        }
    };
}

#[cfg(test)]
mod test
{
    extrum!
    {
        #[derive(PartialEq)]
        enum Extrum: u8
        {
            FOO = 1,
            BAR = 2,
            BAZ = 3,
        }
    }

    implement_display![Extrum];

    #[test] fn test_essential_1() { assert_eq!(Extrum::FOO, Extrum::from_raw(1)); }
    #[test] fn test_essential_2() { assert_eq!(Extrum::BAR, Extrum::from_raw(2)); }
    #[test] fn test_essential_3() { assert_eq!(Extrum::BAZ, Extrum::from_raw(3)); }

    #[test] fn test_essential_4() { assert_eq!(Extrum::FOO, 1); }
    #[test] fn test_essential_5() { assert_eq!(Extrum::BAR, 2); }
    #[test] fn test_essential_6() { assert_eq!(Extrum::BAZ, 3); }

    #[test] fn test_essential_7() { assert_eq!(Extrum::from_raw(1), 1); }
    #[test] fn test_essential_8() { assert_eq!(Extrum::from_raw(2), 2); }
    #[test] fn test_essential_9() { assert_eq!(Extrum::from_raw(3), 3); }

    #[test] fn test_essential_10() { assert_eq!(Extrum::FOO.into_raw(), 1); }
    #[test] fn test_essential_11() { assert_eq!(Extrum::BAR.into_raw(), 2); }
    #[test] fn test_essential_12() { assert_eq!(Extrum::BAZ.into_raw(), 3); }

    #[test] fn test_essential_13() { assert_eq!("Extrum::".to_string() + Extrum::FOO.name(), format!("{:?}", Extrum::FOO)); }
    #[test] fn test_essential_14() { assert_eq!("Extrum::".to_string() + Extrum::BAR.name(), format!("{:?}", Extrum::BAR)); }
    #[test] fn test_essential_15() { assert_eq!("Extrum::".to_string() + Extrum::BAZ.name(), format!("{:?}", Extrum::BAZ)); }

    #[test] fn test_essential_16() { assert_eq!(Extrum::FOO.name(), "FOO"); }
    #[test] fn test_essential_17() { assert_eq!(Extrum::BAR.name(), "BAR"); }
    #[test] fn test_essential_18() { assert_eq!(Extrum::BAZ.name(), "BAZ"); }

    #[test] fn test_display_1() { assert_eq!(format!("{}", Extrum::FOO), "FOO"); }
    #[test] fn test_display_2() { assert_eq!(format!("{}", Extrum::BAR), "BAR"); }
    #[test] fn test_display_3() { assert_eq!(format!("{}", Extrum::BAZ), "BAZ"); }
}
